name: freemars # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.8.7.5' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Turn based free strategy game about colonizing Mars.
description: |
   It is the year 2077, for the first time in its history mankind has finally began the colonization of another planet. Will the pioneers from Earth succeed in colonizing their new home or will they fail to survive against the harsh and inhospitable conditions of the Red planet? Free Mars is a turn based strategy game about colonizing Mars.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  freemars_icon.png
title: FreeMars

apps:
  freemars:
    command: FreeMars.sh
parts:
  freemars:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      freemars: build/
      freemars.1: man/man1/

architectures:
  - build-on: amd64

